### PR TITLE
feat: add DingTalk social login

### PR DESCRIPTION
**Pull request by renyijiu**
1. Added DingTalk OAuth2 Login

DingTalk login

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Comment by piotrmsc** [comment]
Hey @renyijiu , thank you for the contribution and video capture of the flow :) That helps already!

I will review your code changes,  did a quick look now and would like to read a little first about API of ding talk and integration with it, does this service provider have English documentation? If so, can you link it here?

**Comment by aeneasr** [comment]
Thank you for the PR, I have made some adjustments to the code base to reduce code duplication. Can you PTAL and ensure my changes still work with DingTalk?

**Comment by renyijiu** [comment]
> Thank you for the PR, I have made some adjustments to the code base to reduce code duplication. Can you PTAL and ensure my changes still work with DingTalk?

👍🏻 I will test it and give the results later. So far I see that one lint rule did not pass

**Comment by renyijiu** [comment]
> Thank you for the PR, I have made some adjustments to the code base to reduce code duplication. Can you PTAL and ensure my changes still work with DingTalk?

@aeneasr I made a small modification and then tested it locally to verify that there is no problem.

**Comment by piotrmsc** [comment]
> [https://open.dingtalk.com/document/orgapp-server/tutorial-obtaining-user-personal-information，](https://open.dingtalk.com/document/orgapp-server/tutorial-obtaining-user-personal-information%EF%BC%8C) sorry about this, I consulted the customer service of dingtalk, the reply is that there is only Chinese version of the document, you may need to use google translate to read it.

Thx for the link, it's bit hard to translate 😅  :D

**Comment by aeneasr** [comment]
Great Job! :)

**Pull request merged**
