### PR TITLE
autogen(docs): add instruction for creating user

### PR DESCRIPTION
**Pull request by nanikjava**
## Related issue

Going through the documentation http://localhost:3000/kratos/docs/next/self-service/flows/user-registration from `master` branch found out there is a gap in the document. It is not clear on how to create user registration using API call.

## Proposed changes

This PR add a small section on showing step showing how to add a user via API using `curl`

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you, this looks great! The CI is failing because some files are formatted incorrectly. To format them, run:

```
$ make format
$ git commit -a -m "styles: format code"
$ git push
```

Thank you!

**Comment by nanikjava** [comment]
> Thank you, this looks great! The CI is failing because some files are formatted incorrectly. To format them, run:
> 
> ```
> $ make format
> $ git commit -a -m "styles: format code"
> $ git push
> ```
> 
> Thank you!

Thanks.

I committed the changes before reading your comment :)

I've squashed the commit into single commit instead of separate commit.

**Review by aeneasr — APPROVED** [review]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Comment by aeneasr** [comment]
I made a small change and pushed it to #1541 so closing this via merging the other :)

**Pull request closed without merging**
