### PR TITLE
feat: Add ability to import user password credentials

### PR DESCRIPTION
**Pull request by samcgardner**
This change implements a very simple way of adding a user to Kratos with a known password, either in clear text or in one of the supported hashes. The user can also be added in a Verified status. This is intended to support a simple way of importing an existing user database.

I am submitting on behalf of a colleague due to previously discussed issues with internal approval.

## Related issue(s)

[Issue 605](https://github.com/ory/kratos/issues/605)

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you, this looks great! Could you please sign the CLA (just two clicks), then we can start with progressing on the review :)

**Comment by alan994** [comment]
Any update on this? We really need this feature. Also, some support for extending `hasher` implementations would be great (perhaps in form of an external API call), but this is great for now.

**Comment by vinckr** [comment]
> Any update on this? We really need this feature. Also, some support for extending `hasher` implementations would be great (perhaps in form of an external API call), but this is great for now.

Hey Alan, 
we don't give out concrete timelines for open source features, to protect our contributors and maintainers wellbeing. 
That being said this is an important feature that will *soon* land, please be patient 🙏 
We are also always open to contributions 👍
Also see our open source roadmap: https://www.ory.sh/docs/ecosystem/roadmap

**Comment by samcgardner** [comment]
Hey ORY team, I just want to check you don't need any further input from me to drive this forward

**Pull request closed without merging**
