### PR TITLE
docs: minor improvements

### PR DESCRIPTION
**Pull request by zepatrik**
- fix: emptyResponse description wrapping to new line
- feat: rename "Revoke and Invalidate a Session" to reflect the most common use-case (analogous to other endpoints)

## Related issue

Was quite hard to find how to logout an API client: https://ory-community.slack.com/archives/C012RJ2MQ1H/p1612778929119900

@schreddies

### CODE REVIEW

**Review by aeneasr — APPROVED** [review]

**Comment by aeneasr** [comment]
Actually merge issues :(

**Comment by zepatrik** [comment]
Resolved :wink:

**Comment by schreddies** [comment]
@zepatrik @aeneasr Thanks!

**Comment by aeneasr** [comment]
Now, compilation fails.

**Pull request merged**
