### PR TITLE
feat: rate limit failed password attempts

### PR DESCRIPTION
**Pull request by djcrabhat**
Adding a per Identifier+requesting IP [Limiter](https://pkg.go.dev/golang.org/x/time/rate#Limiter), per @aeneasr 's [lovely explanation](https://github.com/ory/kratos/issues/654#issuecomment-728958470).  (hope that suffices for a design doc :))

Starts by making a repeated failed attempt for a user from the same IP wait for 1s.  We double this wait time for every subsequent failed attempt, up to the configurable `selfservice.methods.password.config.rate_limit_max_duration` (Default 30s).  Resets the limiter on successful login.  Adds a background goroutine to forget any tracked attempts older than 10 minutes.

## Related issue(s)

#654 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

## Further Comments
I _think_ an in-memory tracking of failed attempts is good enough here.  I don't think it's worth persisting to the DB for, far too chatty and a drag on performance to be worth the coordinated effort across nodes.

### CODE REVIEW

**Review by aeneasr — COMMENTED** [review]
This is awesome! Thank you :)

One problem I see right now (we do not have to address it immediately) is that as we scale Ory Kratos (e.g. run 3 pods of it), the rate limit will be per node! So I think it would be good to have a rate limit backend (in memory is a good first step) which can be configured. I think we could have, in the future:

1. in memory / per process
2. in SQL
3. in a high performance system (e.g. redis)

Maybe we could lay the foundation for such a design in this PR and implement in memory, and follow up in another PR with SQL?

**Comment by aeneasr** [comment]
By the way, maybe it makes sense to use an existing rate limiting algo? E.g. https://github.com/uber-go/ratelimit

**Comment by djcrabhat** [comment]
Certainly @aeneasr , would be happy to.  Was hoping this would be a start of the conversation on this feature, propose _something_ with some code, and would be happy to iterate on it.  And will definitely look at uber's library there, I just took go's super simple library as a starter./

Thanks for your support and helpful suggestions.  Will get on those today.

**Comment by aeneasr** [comment]
Absolutely! And thank you so much for the contribution:) And happy new year!! :)

**Comment by djcrabhat** [comment]
Sorry, time got away from me over January.  Still want to clean this up!

**Comment by aeneasr** [comment]
Would be awesome! I think this is a great feature!

**Pull request closed without merging**
