### PR TITLE
feat: increase courier watchMessages polling delay from 1 second to 30

### PR DESCRIPTION
**Pull request by frederikhors**
The database is flooded with calls all the time for this!

Related to https://github.com/ory/kratos/issues/466.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Review by aeneasr — CHANGES_REQUESTED** [review]
Thank you for the PR @frederikhors

I don't think this is a good solution though. It will take up to 30 seconds + email send delay, before the email arrives at the user. So the user has to wait half a minute before they receive their account recovery code, or their login code. That's unfortunately not acceptable and we would like to keep the watcher at one second for the time being.

**Comment by frederikhors** [comment]
Ok. I get that but I think 30 seconds is a decent wait time for anyone.

What about 15?

**Comment by jonas-jonas** [comment]
Maybe, instead of using a hard-coded value, we can make this configurable, by adding an optional key `courier.dispatch-interval`, that defaults to 1s?

**Comment by aeneasr** [comment]
Telling the truth, I think this should just stay as is. Adding one QPS to the database should not really have a big effect on overall query performance. I also don't want this to be configurable in Ory Network.

**Comment by frederikhors** [comment]
I think the suggestion to make it configurable is good. Please. Please.

**Comment by aeneasr** [comment]
What exactly is the problem you are trying to solve with this? Is there a negative effect you are experiencing?

If configurable, it should be at most a CLI flag, but not a configuration setting in the YAML config.

**Comment by frederikhors** [comment]
> Is there a negative effect you are experiencing?

Yep. A very small DB (many DBS) and no need to send courier emails.

If you prefer to use a CLI flag ok. Thanks anyway.

**Comment by aeneasr** [comment]
If you don’t need to send emails from Kratos, you could also just not run the courier? 🤔

**Comment by frederikhors** [comment]
> If you don’t need to send emails from Kratos, you could also just not run the courier? 🤔

Sorry I meant not as fast as 1 second delay.

I'm fine waiting 30 seconds or more.

**Comment by aeneasr** [comment]
https://github.com/ory/kratos/pull/3601 will make this configurable

**Pull request closed without merging**
