### PR TITLE
fix: cors headers not added to the response #2922

### PR DESCRIPTION
**Pull request by kstasik**
CORS response headers not added to the response:

```
access-control-allow-credentials: true
access-control-allow-origin: ...
access-control-expose-headers: Content-Type, Set-Cookie
```

## Related issue(s)

#2922 

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

## Further Comments

I just wanted to quickly fix the issue. I noticed that upgrading the docker image breaks CORS. Checked the changes before releases and reverted the cause of the problem.

BTW: I noticed that response headers are added by the middleware but they disappear somehow during the processing of the request:

```
[cors] 2022/12/06 22:12:48   Actual response added headers: map[Access-Control-Allow-Credentials:[true] Access-Control-Allow-Origin:[http://....] Access-Control-Expose-Headers:[Content-Type, Set-Cookie] Vary:[Origin]]
```

Maybe someone with larger knowledge about negroni and libraries knows a better fix for this issue (order of middlewares etc.).

### CODE REVIEW

**Review by alnr — APPROVED** [review]

**Comment by alnr** [comment]
Thanks!

**Comment by vladyslav2** [comment]
@alnr @vinckr can you guys update your docker images on dockerhub https://hub.docker.com/r/oryd/kratos/tags?
seems like latest still haven't updated yet

thank you!

**Comment by vinckr** [comment]
Hey @vladyslav2 
latest is this release https://github.com/ory/kratos/releases/tag/v0.11.0, which is also latest on docker hub at the time of writing: https://hub.docker.com/layers/oryd/kratos/v0.11.0/images/sha256-7f409befc77c419fbe0ac3b26719985b5534786b9f5dabf986528f7a8a5861e4?context=explore

**Comment by alnr** [comment]
A release for including the CORS fix has not yet been tagged. If you require this fix right now, consider building kratos from source. Should be straightforward 👍

**Comment by vladyslav2** [comment]
@alnr already did.
But it would be great to have it in the docker hub at some point

**Comment by alnr** [comment]
Kratos v0.11.1 is out now 👍

**Comment by vladyslav2** [comment]
thanks

**Pull request merged**
