### PR TITLE
fix: TOTP invalid code and/or 500 error

### PR DESCRIPTION
**Pull request by kszafran**
Fixes a 500 error if TOTP is removed and then re-added in the same flow.

It also fixes another related bug, that can be reproduced with https://github.com/ory/kratos-selfservice-ui-react-nextjs:
1. go to settings
2. change your name (or email, or whatever)
3. try to set up TOTP
4. "invalid code"

The reason is that because the `InternalContext` is not reset properly in `PostSettingsHook`, the flow will have a new QR code and secret key (`UI` is reset), but the internal context will keep the old TOTP secret.

In the case of the original issue, `InternalContextKeyURL` is deleted from `InternalContext` when TOTP is removed, and since it's not set properly in `PostSettingsHook`, when we try to re-add TOTP, we get 500, because `InternalContextKeyURL` is missing.

## Related issue(s)

https://github.com/ory/kratos/issues/2680

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

## Further Comments

WebAuthn is most likely affected by the same bug, but I didn't any tests there. I wasn't able to run WebAuthn tests locally, because of this error:
```
cy.task('resetCRI') failed with the following error:

The 'task' event has not been registered in the plugins file. You must register it before using cy.task()
```

### CODE REVIEW

**Review by aeneasr — APPROVED** [review]
Great find, thank you!

**Comment by kszafran** [comment]
@aeneasr I fixed the failing `lookup/settings_test.go` by changing the assertion from:
```go
assert.Equal(t, "{}", gjson.GetBytes(actualFlow.InternalContext, ...
```
to
```go
assert.Empty(t, gjson.GetBytes(actualFlow.InternalContext, ...
```
I haven't looked too deep into it, but my initial guess is that the test was relying on the buggy behavior, where the internal context was not reset properly. There is already an assertion like this (using `assert.Empty(t, ...`) in another place in the file, so I'm assuming the behavior is correct.

**Comment by kszafran** [comment]
And now I also fixed `webauthn/settings_test.go` by changing an assertion. I hope it makes sense, but since I'm not familiar with the WebAuthn flow, I'm not exactly sure.

**Comment by kszafran** [comment]
And now some snapshot comparisons fail in WebAuthn tests, even though they passed before 😞 .

**Review by aeneasr — DISMISSED** [review]

**Comment by aeneasr** [comment]
Yeah sorry about that, we had some breaks on master :( Should all be fixed now

**Pull request merged**
