### PR TITLE
feat: allow importing hmac hashed passwords

### PR DESCRIPTION
**Pull request by tristankenney**
Hello folks! 

I've had a crack at implementing hmac support for password imports

I've followed the approach of base64 encoding and delimiting the string with `$` as seems to be the convention.

The basic format is `$hmac-<hashfunction>$<base64 encoded hash>$<base64 encoded key>` e.g.: 

```
# password = test; key=key; hash function=sha
$hmac-sha1$NjcxZjU0Y2UwYzU0MGY3OGZmZTFlMjZkY2Y5YzJhMDQ3YWVhNGZkYQ==$a2V5
```

I yoinked a [subset of the digests from Auth0](https://auth0.com/docs/manage-users/user-migration/bulk-user-import-database-schema-and-examples#hmac)

NB: This is my first time writing any Go, so _please_ point out areas for improvement

## Related issue(s)
* #2422 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Review by aeneasr — COMMENTED** [review]
Very nice! This looks very good for your first time writing Go! We'll need to do another pass on the security aspects but I doN't see any big blockers. @jonas-jonas WDYT?

**Comment by aeneasr** [comment]
Oh and could you please add docs for this here: https://github.com/ory/docs/edit/master/docs/kratos/manage-identities/25_import-user-accounts-identities.mdx

**Review by jonas-jonas — DISMISSED** [review]
Very nice changes! Thanks for the patch!

**Review by aeneasr — APPROVED** [review]

**Comment by tristankenney** [comment]
Oh wow! You move quick, @aeneasr – I was coming back to add in the documentation now

**Comment by aeneasr** [comment]
Would still appreciate it if you could add a PR for docs :) Thanks so much!

**Comment by tristankenney** [comment]
Done, @aeneasr – https://github.com/ory/docs/pull/1580

**Pull request merged**
