### PR TITLE
docs: Add Chinese version README file

### PR DESCRIPTION
**Pull request by panda8z**
## Proposed changes

让中国开发者也能读懂 Kratos 是 做什么的。未来的日子里，我会翻译更多的文档。
Let Chinese developers also understand what Kratos does.
In the coming days, I will translate more documents which in docs/docs folder.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by xlanor** [comment]
I just glanced at it and I feel like this is a fairly accurate translation! However, I do have one suggestion: Even though it is not explicitly stated in the current readme, if you were to go down the path of adding READMEs for multiple languages, it should probably be explicitly stated that the preferred language for emails and issues should be English, in order to facilitate communication.

这的确看起来非常准确,但是我有一个建议: 若要把readme翻成不同的语言, 可能在readme之内加多一个部分提醒用户者在Github或电邮之内使用英文,让大家能够容易沟通

**Comment by panda8z** [comment]
> I just glanced at it and I feel like this is a fairly accurate translation! However, I do have one suggestion: Even though it is not explicitly stated in the current readme, if you were to go down the path of adding READMEs for multiple languages, it should probably be explicitly stated that the preferred language for emails and issues should be English, in order to facilitate communication.
> 
> 这的确看起来非常准确,但是我有一个建议: 若要把readme翻成不同的语言, 可能在readme之内加多一个部分提醒开发者在Github或电邮之内使用英文,让大家能够容易沟通

Right. I'm very grateful to your suggestion. I'll close this PR and update the README-CH.md  file.

**Comment by vinckr** [comment]
Wow, thanks for this contribution 🎉

**Comment by aeneasr** [comment]
Hello and thank you very much for the translation! We love that we have an international community which is also helping in translating the documentation.

Unfortunately we do not have anyone in the team speaking / reading / writing chinese. So one problem we are faced with is that we do not understand what is written in the README. This is problematic because there are attack vectors which add malicious instructions in translations (e.g. "use this script to install ory kratos" and it actually downloads malware). How could we ensure that the translation is accurate, benevolent, and up to date?

Thank you for your work and thoughts on this!

**Comment by panda8z** [comment]
> Hello and thank you very much for the translation! We love that we have an international community which is also helping in translating the documentation.
> 
> Unfortunately we do not have anyone in the team speaking / reading / writing chinese. So one problem we are faced with is that we do not understand what is written in the README. This is problematic because there are attack vectors which add malicious instructions in translations (e.g. "use this script to install ory kratos" and it actually downloads malware). How could we ensure that the translation is accurate, benevolent, and up to date?
> 
> Thank you for your work and thoughts on this!

You are absolutely right. To be exact, this is the first time that I have encountered such a problem. As far as the current situation is concerned, I have no better way to solve this problem. It may be necessary to set up a Chinese translation team to discuss this matter together. Or, let's close this PR now.

**Pull request closed without merging**
