### PR TITLE
refactor: Refactored cmd package to match the new Ory CLI structure

### LINKED ISSUE #2435: Inconsistent CLI commands in master
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When building and executing the docker image (via `make docker`) in [current master](https://github.com/ory/kratos/commit/e6b38c253466f9f724d2762b01c18485ed96f648) , I get the following inside the container:

```shell
/ $ kratos version
Unable to determine version because the build process did not properly configure it.
Build Commit:   e6b38c253466f9f724d2762b01c18485ed96f648
Build Timestamp:        2022-04-30T20:39:15Z
/ $ kratos
Usage:
  kratos [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  courier     Commands related to the Ory Kratos message courier
  delete      Delete resources
  format      Helpers for formatting code
  get         Get resources
  hashers     This command contains helpers around hashing
  help        Help about any command
  import      Import resources
  lint        Helpers for linting code
  list        List resources
  migrate     Various migration helpers
  remote      Helpers and management for remote Ory Kratos instances
  serve       Run the Ory Kratos server
  validate    Validate resources
  version     Show the build version, build time, and git hash

Flags:
  -h, --help   help for kratos

Use "kratos [command] --help" for more information about a command.

```

On the other side, when using the [published docker image with version v0.9.0-alpha.3](https://hub.docker.com/layers/kratos/oryd/kratos/v0.9.0-alpha.3/images/sha256-28953d0e7d08a011564afbb9acc76716a076932861e16438c2571347b05de620?context=explore), I get the following:

```shell
~ $ kratos version
Version:                        v0.9.0-alpha.3
Build Commit:   32e36d4e75f888e69653625a52171200b4968a6c
Build Timestamp:        2022-03-25T09:35:43Z
~ $ kratos
Usage:
  kratos [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  courier     Commands related to the Ory Kratos message courier
  hashers     This command contains helpers around hashing
  help        Help about any command
  identities  Tools to interact with remote identities
  jsonnet     Helpers for linting and formatting JSONNet code
  migrate     Various migration helpers
  remote      Helpers and management for remote Ory Kratos instances
  serve       Run the Ory Kratos server
  version     Show the build version, build time, and git hash

Flags:
  -h, --help   help for kratos

Use "kratos [command] --help" for more information about a command.
```

Note the difference in the CLI commands.

As far as I can tell from `cm/root.go` the latter is expected but somehow on master it's not the case.

### Reproducing the bug

For the current master:

```shell
git checkout e6b38c253466f9f724d2762b01c18485ed96f648
make docker
docker run -d --name kratos_master oryd/kratos:latest
docker exec kratos_master kratos version
docker exec kratos_master kratos
```

For the v0.9.0-alpha.3:
```shell
docker run -d --name kratos_090alpha3 oryd/kratos:v0.9.0-alpha.3
docker exec kratos_090alpha3 kratos version
docker exec kratos_090alpha3 kratos
```

### Relevant log output

_No response_

### Relevant configuration

_No response_

### Version

latest and v0.9.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

My goal is to have a docker container with this fix (https://github.com/ory/kratos/issues/2367) since it's not yet published in DockerHub.

### PR DESCRIPTION
**Pull request by carloschida**
Signed-off-by: Carlos Chida <carlos.chida@gmail.com>

With the changes introduced in https://github.com/ory/kratos/commit/73910a329b1ee46de2607c7ab1958ef2fb6de5f4#, the folder/package structure within the package `cmd` didn't match the new Ory CLI structure. These changes address that inconsistency.

## Related issue(s)

Closes #2435.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by carloschida** [comment]
I can't figure out the failure in the linting (`goimports`). It doesn't say which files are wrong.

```
run golangci-lint
  Running [/home/runner/golangci-lint-1.45.2-linux-amd64/golangci-lint run --out-format=github-actions --timeout 10m0s] in [] ...
  Error: File is not `goimports`-ed with -local github.com/ory (goimports)
  Error: File is not `goimports`-ed with -local github.com/ory (goimports)
```

I previously fixed 3 wrong files (https://github.com/ory/kratos/pull/2439/commits/e631eb69058fa6c358af7d0eeeaf0d1b95728a44) with `goimports -local github.com/ory -w .` run in the root of the repo but I just ran it again and this time it produced no results.

**Comment by aeneasr** [comment]
Thank you for the PR! Unfortunately it clashes with some of my work where I have *partially* taken care of the structure. I'll merge my PR first as it contains some logic changes, and then we can merge this one once the conflicts are resolved. It's quite likely that it needs to be redone though as there will be many issues.

**Comment by carloschida** [comment]
Hey, no biggie. Glad to contribute. Let me know if/when I can help any further in this direction. 

Out of curiosity, in which branch is this work you've been doing?

**Comment by aeneasr** [comment]
I just merged it on master - it was: https://github.com/ory/kratos/pull/2431

**Comment by carloschida** [comment]
@aeneasr, do you still see value in this refactoring? I have some spare time to solve the merge conflicts.

**Comment by aeneasr** [comment]
Depends a bit, maybe you could quickly lay out what your target structure looks like? One challenge will maybe be to reuse the test tooling we have for identities.

I guess it would be easiest to start a new PR with the changes

**Comment by aeneasr** [comment]
While the PR is being worked on I will mark it as a draft. That declutters our review backlog :)

Once you're done with your changes and would like someone to review them, mark the PR as ready and request a review from one of the maintainers.

Thank you!

**Pull request closed without merging**
