### PR TITLE
fix: swagger specs for settings api's browser flow

### PR DESCRIPTION
**Pull request by davidcheung**
## Related issue
Closes https://github.com/ory/sdk/issues/43

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by zepatrik** [comment]
The swagger schema is generated from code comments, you will have to update it here https://github.com/ory/kratos/blob/master/selfservice/flow/settings/handler.go#L152 and then run `make sdk`. Or let the CI do the work :wink:

**Comment by zepatrik** [comment]
So the CI did regenerate the SDK but could not push the commit. Is this intended behavior for forks @aeneasr ? It will be generated on master anyway so I will merge this now.

**Comment by aeneasr** [comment]
@zepatrik I guess the push should go to the fork but I think we have currently configured it to push to the upstream. I can look into this if I have some time.

**Comment by zepatrik** [comment]
Yes, that's the current behavior. It is fine like this IMO as well because the SDK will be regenerated on master anyway. Tracked it as https://github.com/ory/ci/issues/44

**Pull request merged**
