### PR TITLE
Fix 132

### LINKED ISSUE #132: Enable CockroachDB test suite and integration
Upstream:

* https://github.com/gobuffalo/fizz/pull/69
* https://github.com/gobuffalo/pop/pull/491

### PR DESCRIPTION
**Pull request by evalsocket**
## Related issue
It will close #132 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation within the code base (if appropriate)
- [x] I have documented my changes in the [developer guide](https://github.com/ory/docs) (if appropriate)

### CODE REVIEW

**Comment by aeneasr** [comment]
Hm, looks like pop is not properly parsing the CockroachDB URL.

**Comment by evalsocket** [comment]
@aeneasr  what could be the possible solution ?

**Comment by aeneasr** [comment]
We have to create a PR against gobuffalo/pop to fix that - and also an issue probably.

**Comment by evalsocket** [comment]
@aeneasr  issue is created on [gobuffalo/pop]( https://github.com/gobuffalo/pop/issues/513)

**Comment by aeneasr** [comment]
Closing because upstream issue was also closed: https://github.com/ory/kratos/issues/136#issuecomment-588126840

**Comment by aeneasr** [comment]
Sorry, I closed the wrong issue

**Pull request closed without merging**
