### PR TITLE
fix: adds missing gitlab to list of supported oidc providers

### PR DESCRIPTION
**Pull request by NickUfer**
## Proposed changes

Adds gitlab to list of supported providers in error message.

## Checklist

- [X] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [X] I have read the [security policy](../security/policy).
- [X] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [X] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by zepatrik** [comment]
Nice catch, could you automate that list generation though? That way it will be always up to date.
My suggestion would be to use a pattern similar to this: https://play.golang.org/p/ktNUWwnWb9R

**Comment by zepatrik** [comment]
Sorry for the crude example but I hope it explains the idea.

**Comment by zepatrik** [comment]
You can omit the custom type though and just go with strings, that should be fine.

**Comment by zepatrik** [comment]
https://github.com/ory/kratos/blob/master/selfservice/strategy/oidc/provider_config.go#L19-L21 is also out of date, sorry for all the spam.

**Comment by NickUfer** [comment]
> Nice catch, could you automate that list generation though? That way it will be always up to date.
> My suggestion would be to use a pattern similar to this: https://play.golang.org/p/ktNUWwnWb9R

Sure. I also thought about refactoring this but my second thought was maybe it's on purpose for simplicity or something.

**Comment by zepatrik** [comment]
I guess it was because of laziness by @aeneasr :wink:

**Comment by NickUfer** [comment]
I hope this is not too over engineered

**Comment by zepatrik** [comment]
Looking good, one other idea I had was to use the [python switch approach](https://stackoverflow.com/a/11479840). You would have to iterate over the map but I think this is nicer 😉

**Review by zepatrik — APPROVED** [review]

**Pull request merged**
