### PR TITLE
chore: fix mermaid

### PR DESCRIPTION
**Pull request by vinckr**
## Related issue

Fixes the currently broken https://www.ory.sh/kratos/docs/concepts/identity-data-model page

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Review by aeneasr — COMMENTED** [review]
Thank you very much for your contribution to the documentation! Due to the way [Docusaurus](https://docusaurus.io) versioning works, you need to make the changes in two locations:

- `docs/versioned_docs/version-v{version}/path/to/file`
- `docs/docs/path/to/file`

Without making them in both locations, the changes will most likely be lost when releasing another version. Thank you! :)

**Comment by vinckr** [comment]
Done :). 
Tested and working in both versions locally.

**Comment by vinckr** [comment]
Hey @aeneasr,
This got overwritten again in 
https://github.com/ory/kratos/commit/1d3a4349a394210dc7d96437eff9957d32bb8fc5

> autogen(docs): generate cli docs 

breaking https://www.ory.sh/kratos/docs/next/concepts/identity-data-model . 

I will look into what happens, but if you already have an idea where to look, let me know. 
I suspect it is something with text-runner or formatting, that changes the mermaid graphs. 

Maybe we just need to ignore what is inside the <Mermaid> when formatting?

**Comment by aeneasr** [comment]
Shit yeah that looks like an issue from [prettier](https://prettier.io). Maybe we are using an older version in the cli docs generator? The script can be found here: https://github.com/ory/ci/blob/master/src/scripts/docs/cli.sh#L20

You can try this yourself by making the change, then

```
$ cd docs
$ npm i
$ npm run format
```

and check the result

**Comment by aeneasr** [comment]
@vinckr the problem is that the `identity-data-model` was an `.md` file. `.md` file do not support React components (well it still works in docusaurus but it should not work). prettierJS sees the `.md` file and interprets it as a regular markdown file. However, the Mermaid thing is a React component - hence the formatting is messed up. By updating the file to be a `.mdx` file, formatting no longer breaks this.

**Comment by vinckr** [comment]
Awesome, that makes total sense!

**Pull request merged**
