### PR TITLE
feat: issue#1221 unexpected email

### LINKED ISSUE #1221: Receive the verification email every time when I update my password
**Describe the bug**

I registered an account but did not verify the email address. I received an verification email every time  I change my password. This seems unexpected.
Is this intentional? Is there a way to stop this?

**Reproducing the bug**

_Server logs_

_Server configuration_

**Expected behavior**
No email should be sent when I just update my password.

**Environment**

- Version: v1.2.3, git sha hash
- Environment: Debian, Docker, ...

**Additional context**

### PR DESCRIPTION
**Pull request by cwei-wish**
unexpected varification email

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by cwei-wish** [comment]
@aeneasr Hi, I added a new field in veriableAddress.  But when I run test I got error:
`time=2021-04-26T15:46:56-04:00 level=error msg=An error occurred while handling a request audience=application error=map[message:sqlite select many: no such column: identity_verifiable_addresses.email_initiated] http_request=map[headers:map[accept:application/json accept-encoding:gzip user-agent:OpenAPI-Generator/1.0.0/go] host:127.0.0.1:55087 method:GET path:/identities/454aa66d-d4a0-4f5f-ae9a-a406e7914db2 query:<nil> remote:127.0.0.1:55088 scheme:http] http_response=map[status_code:500] service_name= service_version=
`
I am thinking I need to make changes to SQL too. But may I get some guidance how to do that. When I follow https://github.com/ory/kratos/tree/master/persistence/sql here, it complains ory is not a command. Thanks

**Comment by aeneasr** [comment]
I have created a guide on how to add migrations: https://github.com/ory/docs/blob/master/docs/docs/ecosystem/contributing.md#sql-migrations

I hope this helps!

**Review by aeneasr — CHANGES_REQUESTED** [review]
It would probably make sense to use the status instead: 

https://github.com/ory/kratos/blob/master/identity/identity_verification.go#L17-L18

We could add a new status `sent` and then only initiate emails for `PENDING` status.

**Comment by cwei-wish** [comment]
> I have created a guide on how to add migrations: https://github.com/ory/docs/blob/master/docs/docs/ecosystem/contributing.md#sql-migrations
> 
> I hope this helps!

Yes looks nice. It's definitely very helpful. Thanks and I will continue working on this.

**Comment by cwei-wish** [comment]
> It would probably make sense to use the status instead:
> 
> https://github.com/ory/kratos/blob/master/identity/identity_verification.go#L17-L18
> 
> We could add a new status `sent` and then only initiate emails for `PENDING` status.

sounds good. will make the changes

**Pull request closed without merging**
