### PR TITLE
Minor Grammar changes

### PR DESCRIPTION
**Pull request by williamohara**
made some minor changes for subject verb agreement and made the last one a bit more clear.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Review by zepatrik — CHANGES_REQUESTED** [review]
Can you add the changes to the `faq.yml` as described at the beginning of the file? Thanks a lot 👍

**Comment by aeneasr** [comment]
Are you still up for the changes? :) If you need any help, let us know!

**Comment by aeneasr** [comment]
@vinckr

**Comment by vinckr** [comment]
I will change it tomorrow! 

Want to implement a proper pipeline to make changes like this more convenient for users also. 
The FAQ should be generated out of .md files, so people can easily makes edits and create new items. 
I am thinking a dedicated repo ory/faq or do you think its better to do it in ory/docs/faq ?

**Comment by aeneasr** [comment]
Adding another repository just makes it harder to find for people and adds no benefits. FAQ are part of the documentation and should be kept there!

**Pull request closed without merging**
