### PR TITLE
feat: order sessions by created_at

### PR DESCRIPTION
**Pull request by jonas-jonas**
## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Review by aeneasr — COMMENTED** [review]
Is created_at indexed? If not this will be slow

**Comment by jonas-jonas** [comment]
Without any new index (current status quo):

| QUERY PLAN                                                                                                                                                                                                               | --row-header |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------ |
| Limit  (cost=8.18..8.19 rows=1 width=333)                                                                                                                                                                                |              |
|   ->  Sort  (cost=8.18..8.19 rows=1 width=333)                                                                                                                                                                           |              |
|         Sort Key: created_at DESC, id                                                                                                                                                                                    |              |
|         ->  Index Scan using sessions_token_nid_idx on sessions  (cost=0.14..8.17 rows=1 width=333)                                                                                                                      |              |
|               Index Cond: (nid = '187f702b-946d-4682-8e92-204cfc699e06'::uuid)                                                                                                                                           |              |
|               Filter: ((created_at < '1999-01-08 00:00:00'::timestamp without time zone) OR ((created_at = '1999-01-08 00:00:00'::timestamp without time zone) AND (id > '187f702b-946d-4682-8e92-204cfc699e06'::uuid))) |              |

With `CREATE INDEX idx_sessions_nid_created_at_id ON sessions (nid, created_at DESC, id ASC);`:

| QUERY PLAN                                                                                                                                                                                                         | --row-header |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------ |
| Limit  (cost=0.14..8.17 rows=1 width=333)                                                                                                                                                                          |              |
|   ->  Index Scan using idx_sessions_nid_created_at_id on sessions  (cost=0.14..8.17 rows=1 width=333)                                                                                                              |              |
|         Index Cond: (nid = '187f702b-946d-4682-8e92-204cfc699e06'::uuid)                                                                                                                                           |              |
|         Filter: ((created_at < '1999-01-08 00:00:00'::timestamp without time zone) OR ((created_at = '1999-01-08 00:00:00'::timestamp without time zone) AND (id > '187f702b-946d-4682-8e92-204cfc699e06'::uuid))) |              |

I added the index to the migrations. LMK if you see room improvements. cc @alnr PTAL as well. Ty :)

**Review by alnr — APPROVED** [review]
PR and index LGTM.

Do we maybe want to add tests to verify:
- results are actually ordered by `created_at`
- make sure we're not missing items near a page break when they have identical `created_at` times.

Maybe that's already tested in ory/x? Could also be overkill for this.

**Comment by aeneasr** [comment]
Typically, ordering would be done by ID for page pagination to avoid the ambiguity around having two items with the same timestamps. I do understand though why created_at makes sense to order by in this case.

**Comment by jonas-jonas** [comment]
> Typically, ordering would be done by ID for page pagination to avoid the ambiguity around having two items with the same timestamps. I do understand though why created_at makes sense to order by in this case.

That's exactly the point of the `MapPageToken`. It consists of both the `created_at` timestamp and the `ID`, and will fall back on the `ID`, if there are collisions.

This is the statement (note the `OR` clause):

```sql
SELECT * FROM sessions AS sessions WHERE nid = $1 AND ("sessions"."created_at" < $2 OR ("sessions"."created_at" = $3 AND "sessions"."id" > $4)) ORDER BY "sessions"."created_at" DESC, "sessions"."id" ASC LIMIT 4
```

**Pull request merged**
