### PR TITLE
Make explicit the ID of the default schema

### PR DESCRIPTION
**Pull request by jordanisaacs**
## Proposed changes

Add one line to the config docs to mention the ID of the default schema. This is useful for using the schema/{id} API. It is not mentioned anywhere else in the docs.

## Checklist

- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x ] I have read the [security policy](../security/policy).
- [x ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x ] I have added tests that prove my fix is effective or that my feature
      works.
- [x ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by Benehiko** [comment]
Hey @jordanisaacs 

Thank you for updating the docs!
Due to the way [Docusaurus](https://docusaurus.io/) versioning works, you need to make the changes in two locations:
- docs/versioned_docs/version-v{version}/path/to/file
- docs/docs/path/to/file

Otherwise the changes will be lost on next release!

**Comment by zepatrik** [comment]
Also, the changes are in an auto-generated file. Please add the description here: https://github.com/ory/kratos/blob/master/driver/config/.schema/config.schema.json

**Comment by aeneasr** [comment]
@vinckr can you fix this in another PR?

**Comment by vinckr** [comment]
Sure, noted 🐝 .

**Comment by jordanisaacs** [comment]
Sorry I got a bit sidetracked. Do I need to do the edit in both the config.schema.json and the docs? Or just the json file.

**Comment by aeneasr** [comment]
Just the JSON :)

**Comment by jordanisaacs** [comment]
I put a mention of the ID in the description of default_schema_url as that seemed like the right spot.

**Comment by aeneasr** [comment]
Thank you!

**Pull request merged**
