### PR TITLE
Feature 136

### PR DESCRIPTION
**Pull request by evalsocket**
## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [ ] I have read the [security policy](../security/policy)
- [ ] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation within the code base (if appropriate)
- [ ] I have documented my changes in the [developer guide](https://github.com/ory/docs) (if appropriate)

### CODE REVIEW

**Comment by aeneasr** [comment]
Let me know if this is good for a review :)

**Comment by evalsocket** [comment]
@aeneasr sorry for the delay on that issue because of the new year week. I need a review on implementation then I can finish the TODO's.

**Comment by aeneasr** [comment]
No worries!

**Comment by aeneasr** [comment]
Closing because upstream issue was also closed: https://github.com/ory/kratos/issues/136#issuecomment-588126840

**Pull request closed without merging**
