### PR TITLE
Fix docs build

### PR DESCRIPTION
**Pull request by vinckr**
## Related issue
https://github.com/ory/kratos/pull/1179

Docs building correctly again.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Review by zepatrik — COMMENTED** [review]
Just changing this will not fix it, we generate that part:
https://github.com/ory/x/blob/27efc4a6ffef8e5ecb39a5746c64d4af539cf516/clidoc/generate.go#L47-L65

**Comment by aeneasr** [comment]
I think it should fix it or maybe I am mistaken...I made a PR in hydra recently which fixed this

**Comment by zepatrik** [comment]
You did the exact same thing in Hydra as I did in #1179 :joy: https://github.com/ory/hydra/commit/02483ce4c00d53d897830a2aaa7ff0a6d540dc3a#diff-645206cb15580a5a926ee0b374de3fdfc72ba6d0f11897d53d8d4fb9fd8d8b8e

**Comment by aeneasr** [comment]
ok I am getting confused with all the PRs addressing similar things. What should I merge now? Have you tested regeneration of the commands? Or will this again break immediately once it's on master?

**Comment by zepatrik** [comment]
Should work now 😅

**Pull request closed without merging**
