### PR TITLE
fix: corrected typo

### PR DESCRIPTION
**Pull request by dgoosens**
`selfservice.flows.settings.ui_url` should be `selfservice.flows.settings.ui.url`

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by vinckr** [comment]
Thanks for catching this! 
Could you make the same change in the versioned docs, please:
https://github.com/ory/kratos/blob/master/docs/versioned_docs/version-v0.7/configuring.md
🙏

**Review by aeneasr — CHANGES_REQUESTED** [review]
The current value is correct. The key is `ui_url`, not `ui.url`

**Comment by dgoosens** [comment]
Not sure...  
How would a parser be able to make a distinction between those two?

**Comment by aeneasr** [comment]
We have added the appropriate conversions and tests for it!

**Comment by dgoosens** [comment]
> We have added the appropriate conversions and tests for it!

well... yeah....  
if you have a parser that converts all `.` into `_`  
both `selfservice.flows.settings.ui_url` and `selfservice.flows.settings.ui.url` will be converted to `selfservice_flows_settings_ui_url`  
so yeah, there is no error, but this still is not correct

**Comment by aeneasr** [comment]
Using the proposed format would be misleading, because the configuration key is not correct. I will therefore close this, but thank you for elaborating!

**Pull request closed without merging**
