### PR TITLE
feat: add RecoveryURL to recovery code email template data

### PR DESCRIPTION
**Pull request by kszafran**
In some cases we may want to include a link to the recovery UI page (including the flow ID) in the recovery email. That may be useful if the user has closed the page, for example. (In my particular case recovery is triggered by a backend process, so when the user receives the email, they are not on the recovery page and there is no way to pass on the flow ID to them.)

The link added to the template data as `.RecoveryURL` is the exact same link as the one generated by `POST /admin/recovery/code`.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Review by rostyk110 — APPROVED** [review]

**Review by jonas-jonas — CHANGES_REQUESTED** [review]
Thank you for the contribution. We left out the URL intentionally, because the flow is protected against CSRF attacks using a CSRF-token (in cookies and the form fields). 

If you include the link in the email, the flow might open in a different browser, etc., invalidating the flow entirely. Now the user needs to re-do the whole flow, which is not great UX. The account recovery is a crucial part of the account's security and as such needs to be protected well. So I don't think it's a good idea to send links containing such sensitive information to a user.

**Comment by kszafran** [comment]
Hm... are CSRF cookies used here or just the CSRF token in the form fields? If it's the latter, then why would the flow get invalidated? Perhaps I need to test it once more to make sure that this is not the case.

**Comment by jonas-jonas** [comment]
Both a cookie and token are set as part of the flow. You should be able to test this by copying the URL of a flow after submitting the email address into a different browser, and then try to submit the code from the email.

**Comment by kszafran** [comment]
Right, I tested it and I didn't even get to enter the code, because the recovery page got a CSRF error when calling `/self-service/recovery/flows?id=...`... 🤦🏻 

Our whole problem is that we're using the recovery mechanism to fake email invites. I saw a couple of threads regarding the support of invite flows, do you know if there's anyone actively working on it?

**Comment by kszafran** [comment]
Hm... now I see that `POST /admin/recovery/code` works by explicitly disabling CSRF protection. I wonder if that could be made configurable for the recovery flow in general (I'm not quite sure why we even need CSRF cookies on `GET` requests that don't mutate any state). Or perhaps there could be an admin API that instead of fetching the link and the code triggers the email 🤔

**Comment by kszafran** [comment]
I'm basically following https://www.ory.sh/docs/kratos/manage-identities/invite-users except instead of sending emails myself I'm using Kratos' own mechanism. That use case would also be skipping CSRF checks. (I'm not sure to what extent `flow.DangerousSkipCSRFCheck` skips the checks. Here it seems that we can still verify form tokens, just not require cookie tokens on `GET`.)

**Comment by kmherrmann** [comment]
>  I saw a couple of threads regarding the support of invite flows, do you know if there's anyone actively working on it?
It's on the roadmap for the 2nd half of this year, but we haven't gotten to detailed timeline planning. Contributions welcome :)

**Pull request closed without merging**
