### PR TITLE
feat: add instana as possible tracing provider

### PR DESCRIPTION
**Pull request by dadrus**
## Related PR

https://github.com/ory/x/pull/349

As soon as the referenced PR is merged, this PR can be merged as well.

## Proposed changes

Add "instana" as possible value for a tracing provider

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by dadrus** [comment]
@aeneasr: This PR is a follow up PR to ory/x#349 to enable instana to be configured as tracing provider in kratos.

**Comment by dadrus** [comment]
@aeneasr: I'll checking locally (in our cluster) if everything is working as expected. I'll push the go.mod update when this is done.

**Comment by dadrus** [comment]
@aeneasr: In principle, Instana receives everything with the same limitations I've written in https://github.com/ory/hydra/pull/2548#issuecomment-854608853. Having said that the actual Instana support is complete. IMPOV you can merge this PR.

**Comment by aeneasr** [comment]
Thank you, this looks great! The CI is failing because some files are formatted incorrectly. To format them, run:

```
$ make format
$ git commit -a -m "styles: format code"
$ git push
```

Thank you!

**Comment by aeneasr** [comment]
Ok now there's some conflicting files 😓 😅 I'd update it myself but I believe this push rights for maintainers doesn't work on org repos :(

**Comment by aeneasr** [comment]
Looks like a deeper issue with circle CI's cache. I'll try to come up with a fix.

**Comment by aeneasr** [comment]
Once https://github.com/ory/kratos/pull/1411 is merged you can rebase on master and the CI should pass fine.

**Comment by aeneasr** [comment]
it’s merged :)

**Pull request closed without merging**
