### PR TITLE
feat: Team id in slack oidc

### LINKED ISSUE #1408: Include team ID in Slack OIDC response
**Is your feature request related to a problem? Please describe.**

Due to the business requirements in my multi-tenant application I need to make sure that when user clicks "Sign in with Slack" he has indeed an account belonging to the team that was previously connected with the tenant this user is trying to log into. Since I haven't found any way of enforcing it during the redirect-to-Slack phase I thought it can be validated in the post-registration hook.

The slack-go package used inside Slack provider seems to [include team ID in it's response](https://github.com/slack-go/slack/blob/7cf50ec24ab6b4aa751cbfba9351d5fabb4cdcdd/users.go#L144) ([it is definitely included in the Slack response itself](https://api.slack.com/methods/users.identity)). 
~~I'm happy to provide such PR~~ I've went ahead and already created the PR #1409 , but wanted to verify if that is indeed the best solution to this problem.

**Describe the solution you'd like**

The desired change should be as small as adding

`Team: identity.Team.ID,`

after [this line](https://github.com/ory/kratos/blob/2085216bcda837e0ea3194d1b4ad82c215a6b306/selfservice/strategy/oidc/provider_slack.go#L83)

**Describe alternatives you've considered**

I was exploring a possibility to add `&team` param at the end of oauth/authorize request which seems to work fine with the [v2 version of this endpoint](https://api.slack.com/authentication/oauth-v2)

### PR DESCRIPTION
**Pull request by trobinpl**
I did name the property in the Claims struct Team, although I can see it being called something more generic like OrganizationId since Team may be a specific Slack term, but some generic organization seems like something that will be present in many other OAuth providers.

Closes #1408

## Related issue

#1408

## Proposed changes

Reasoning behind this change described in the related issue. Basically it's a small change to include the team ID user belongs to in the Slack OIDC provider response so it's usable information in the hooks

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you very much for your contribution to the documentation! Due to the way [Docusaurus](https://docusaurus.io) versioning works, you need to make the changes in two locations:

- `docs/versioned_docs/version-v{version}/path/to/file`
- `docs/docs/path/to/file`

Without making them in both locations, the changes will most likely be lost when releasing another version. Thank you! :)

**Comment by trobinpl** [comment]
@aeneasr I've included the same documentation change in both locations you've mentioned :)

**Comment by aeneasr** [comment]
Great, thank you!

**Comment by aeneasr** [comment]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Pull request merged**
