### PR TITLE
fix: Broken Oathkeeper paths in the Zero Trust with IAP Proxy guide

### PR DESCRIPTION
**Pull request by zvictor**
Following the guide [Zero Trust with IAP Proxy](https://www.ory.sh/docs/kratos/guides/zero-trust-iap-proxy-identity-access-proxy) has lead to multiple 404 and 401 errors, with not a single URL working (http://127.0.0.1:4455/, http://127.0.0.1:4455/welcome, http://127.0.0.1:4455/login, http://127.0.0.1:4455/auth/login, etc... all failing).

I have tried checking out `v0.8.2-alpha.1`, `v0.8.0-alpha.3`, `v0.7.6-alpha.1`, `v0.5.5-alpha.1`, `v0.4.0-alpha.1`, `v0.3.0-alpha.1`, `v0.2.1-alpha.1`, but all of them had the same problem.

I then checked carefully the [docs](https://www.ory.sh/docs/kratos/guides/zero-trust-iap-proxy-identity-access-proxy) once again and noticed that the content there is different than the content in the yml files. I copied the content from the docs to the yml file and , voila! It worked!

This PR contains the yml files with the changes present at the docs. I intentionally didn't match styling as a way to highlight the discrepancy between source code and docs.

## Steps to reproduce:

```haskell
git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.8.0-alpha.3
docker-compose \
  -f quickstart.yml \
  -f quickstart-oathkeeper.yml \
  up --build --force-recreate
```

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by vinckr** [comment]
Thanks for your PR @zvictor !

Adding @gen1us2k as reviewer, since he updated the guide recently.

**Comment by zvictor** [comment]
If possible, I would like to ask for the `http://127.0.0.1:4455/self-service/<**>` path to be added to the rules as well.
I tried adding it myself but with no success.

In general, all the rules should be revised. CSS & Images are also broken in some cases (e.g. when visiting a second level path).

**Comment by gen1us2k** [comment]
Hello, @zvictor Thanks for sending the pull request. The most configuration was fixed in [this](https://github.com/ory/kratos/pull/2273) pull request. Configuration worked fine and I have no issues with broken css/images. Could you provide any URL examples please so I can test it.

I have another question why do you want to have `/self-service/<**>` URLs behind oathkeeper? The idea of this guide to show an example of securing `selfui-node` container with oathkeeper.

**Comment by zvictor** [comment]
Good points @gen1us2k. I think you're right and this PR is not needed with the changes already made by #2273.
A few comments, though:

**1) The broken assets appear when a 404 error page is rendered in a path not at root level.**

The [self-service](http://127.0.0.1:4455/self-service/methods/oidc/callback/github) url is one example of a broken page.
To fix that, one needs to replace
```html
  <link rel="icon" type="image/png" href="favico.png">
  <link rel="stylesheet" href="theme.css">
  <link rel="stylesheet" href="styles.css">
  <link rel="stylesheet" href="flexboxgrid.min.css">
```
by
```html
  <link rel="icon" type="image/png" href="/favico.png">
  <link rel="stylesheet" href="/theme.css">
  <link rel="stylesheet" href="/styles.css">
  <link rel="stylesheet" href="/flexboxgrid.min.css">
````
The same is needed for `` tags inside `<body>`.

**2) `/self-service/<**>` is needed as soon as OIDC is activated.**

I have just started using Kratos and I am still trying to learn the basics here, so I am not sure if `/self-service/<**>` should be bypassed or be behind oathKeeper.

To be specific, my setup is just the exact same as the one in the guide with one change:
```yml
  methods:
    password:
      enabled: false
    oidc:
      enabled: true
      config:
        providers:
          - id: github
            provider: github
            client_id: xxxxxxx
            client_secret: xxxxxxx
            mapper_url: file:///etc/config/kratos/oidc.github.jsonnet
            scope:
              - user:email
```

My end goal is to build the simplest possible `Login with Github` installation using [Kratos that can provide me with a JWKs URI](https://github.com/ory/kratos/discussions/2302)

**Comment by zvictor** [comment]
> I would like to ask for the http://127.0.0.1:4455/self-service/<**> path to be added to the rules as well.

I figured it out! There is nothing wrong with any code, but with the config at Github. 🫠

I was following the [Authorization callback URL pattern defined at the docs](https://www.ory.sh/docs/kratos/guides/sign-in-with-github-google-facebook-linkedin#github), but that doesn't take into consideration that all calls to Kratos through Oathkeeper should have `/.ory/kratos/public` prepended.

---

Note for future readers:

Set your the *Authorization callback URL* to `http://127.0.0.1:4455/.ory/kratos/public/self-service/methods/oidc/callback/<provider>` when adding third-party login after setting up kratos+oathkeeper.

**Comment by vinckr** [comment]
Thanks for looking into this @zvictor .
As your problem seems to be resolved and the guide is also fixed, this PR can be closed or am I missing something? Closing to declutter, but feel free to reopen if something still needs fixing.

I will make a note to include the fix in the guide or somewhere appropriate - or maybe you want to document it @gen1us2k since you are already in the "topic"?

**Comment by zvictor** [comment]
Yes, it should be closed.
I would only suggest a minor points for improvement but they are up to your interpretation.

The [Authorization callback URL pattern](https://www.ory.sh/docs/kratos/guides/sign-in-with-github-google-facebook-linkedin#github) can be better define, explaining when it should be prepended with `api/kratos/public/self-service`, `.ory/kratos/public/self-service` or just `/self-service`. I assume that you will be focusing more and more in the cloud docs, so open source users might be lost if they have to infer settings based on the cloud docs.

There is yet another minor fix, but I plan on creating a new PR for that.

**Pull request closed without merging**
