### PR TITLE
fix: update correct typo

### PR DESCRIPTION
**Pull request by giautm**
The text for verification code input should be `Verification code` not `Verify code`.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Review by jonas-jonas — DISMISSED** [review]
Thank you, great change.

**Comment by giautm** [comment]
Hello @jonas-jonas, can we merge this soon?

**Comment by aeneasr** [comment]
In that case we indeed need to split the text message and introduce a new message ID. I think that's fine in terms of backwards compatibility

**Comment by jonas-jonas** [comment]
@aeneasr done.

@giautm we're using the "Verify Code" label during the MFA (via TOTP) setup as well, so I reverted the renaming and added new nodes for verification & recovery. Thanks again for spotting & fixing this!

**Review by aeneasr — APPROVED** [review]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Pull request merged**
