### PR TITLE
docs: Replace ampersand

### PR DESCRIPTION
**Pull request by kevgo**
## Proposed changes

Replace `&` with `and` since "identity and access proxy" reads better than "identity & access proxy" to me. This is an extract from #567, it makes sense to discuss this separately. Not feeling strongly about this. If the `&` is part of the branding we can leave it in.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by kevgo** [comment]
Another reason for this change is that the old format leads to anchors containing double-dashes like
`ory-oathkeeper-identity--access-proxy`

**Review by aeneasr — CHANGES_REQUESTED** [review]
Could you please address the merge conflicts? :)

**Comment by aeneasr** [comment]
Also keep in mind that we're using `doctoc` to generate the ToC - not sure if that was what generated the output! Also not sure if this is currently automated...

**Comment by zepatrik** [comment]
Pretty sure it's not automated....

**Comment by kevgo** [comment]
Merge conflicts resolved. 

I was asking about doctoc automation in #748. Happy to look into automating it. Can we assume a Bash environment, i.e. `find` and `xargs`, or does this automation need to run on Windows as well?

**Comment by aeneasr** [comment]
Ah sorry, I must have overlooked that. Yeah - this would run on a ubuntu instance. I think it would make sense to have doctoc execution as part of maybe the docs/build pipeline. @zepatrik what you think?

**Pull request merged**
