### PR TITLE
feat: Add Prometheus monitoring to Public API

### PR DESCRIPTION
**Pull request by mbonnell-wish**
## Proposed changes

Currently, the Prometheus metrics middleware is only used on the Admin API. This PR adds it to the Public API, so that Public API requests may be monitored, as well.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Review by aeneasr — APPROVED** [review]

**Comment by aeneasr** [comment]
Awesome, thank you!

**Comment by mbonnell-wish** [comment]
Thanks for approving!  When do you think we'll be able to publish another release? Having this monitoring would be very important for us.

**Comment by aeneasr** [comment]
This is a bit tricky because we had some breaking changes and are actually waiting for 0.6 to push the next release - which will take some time. In the meanwhile you can use `make docker` and push it to your own repo!

**Comment by mbonnell-wish** [comment]
> This is a bit tricky because we had some breaking changes and are actually waiting for 0.6 to push the next release - which will take some time. In the meanwhile you can use `make docker` and push it to your own repo!

Sounds good, thanks

**Pull request merged**
