### PR TITLE
feat: Allow specifying Sender Name in smtp.from_address

### PR DESCRIPTION
**Pull request by zhming0**
## Proposed changes

Currently, there is no way to configure Email `from` name for Kratos. 

By checking  [ory/mail's source code](https://github.com/ory/mail/blob/e6b733ef914946a8c48b5c81a451c5277d0da0bc/message.go#L133), I am convinced that Kratos is equipped with the ability to handle [RFC-5322](https://tools.ietf.org/html/rfc5322#section-3.4) `mailbox` format. 

This PR introduces a new optional `from_name` properties under `smtp.from_name`.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further comments

If this looks alright, I am happy to raise another PR to update doc or just do it as part of this change too.

### CODE REVIEW

**Comment by zepatrik** [comment]
I am not sure if our jsonschema library supports `format: idn-email`. Can you please add a test here: https://github.com/ory/kratos/tree/master/test/schema
Also, it would be good to have this added in the integration test: https://github.com/ory/kratos/tree/master/test/e2e/cypress/integration/profiles/email
There should be two cases, one with, and one without the sender name.
Thanks a lot :+1:

**Comment by zhming0** [comment]
@zepatrik thanks. You are right, the current jsonschema tool does not support `idn-email`, and I also misunderstood that `idn-email` would allow `Bob <xxx@example.com>`.  🤦‍♂️ 🤦‍♂️ 

Anyway, I have reworked this PR entirely and added a proper integration test. 

Please let me know if this suffice.

**Review by zepatrik — APPROVED** [review]
Nice, this looks good to me :+1:

**Review by aeneasr — APPROVED** [review]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Pull request merged**
