### PR TITLE
feat: Include Credentials Metadata in admin api Missing changes in ha…

### PR DESCRIPTION
**Pull request by martinei**
## Related issue
I am very sorry, but my recently merged PR was missing the essential changes in the handler.
https://github.com/ory/kratos/pull/1274

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by aeneasr** [comment]
Could you add a test for this so that we catch any regressions here? Thank you! :)

**Comment by martinei** [comment]
Hi @aeneasr 

 > Could you add a test for this so that we catch any regressions here? Thank you! :)

I already had a look in the past and would need some guidance here:
The existing test  (TestHandler in handler_test.go) is a kind of  integration test and creates identities using the API. For the new case I'd need an Identity with credentials to test it's retrieval. Creating an identity with credentials can not be done via the api of this handler.

The Option I see would be to create a new Test with a mocked PrivilegedIdentityPool to return deliver an Identity with Credentials. However this would introduce a different style of test.

What do you think?

**Comment by aeneasr** [comment]
In [the test](https://github.com/ory/kratos/blob/master/identity/handler_test.go#L80) you could use `reg.PrivilegedIdentityPool()` directly in the store to create an identity which you later retrieve using HTTP :)

**Review by aeneasr — APPROVED** [review]
Thank you :)

**Pull request merged**
