### PR TITLE
[WIP, discussion needed] Add `i18nText` and `i18nData`

### PR DESCRIPTION
**Pull request by UkonnRa**
## Related issue

https://github.com/ory/kratos/issues/691

## Proposed changes

Add `i18nText` and `i18nData` for i18n

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by UkonnRa** [comment]
In most cases, `context` is `i18nData`, except when related to `expired_at` / `ago`. So we have to separate these two fields

**Comment by zepatrik** [comment]
After having a more detailed look into all the available libraries and formats, I think we should stick with the current approach. We should provide an already formatted text to use for evaluation/development (`"text"`). To customize you will have to write your own translations for every message ID, but we provide the `"context"` in a way so you can use it right as is to pass to your translations. Is there anything we have to change to the format of `"context"` to allow easy usage?
Btw I think it would be awesome to have some community maintained default translations, we would be happy to feature them and provide support.

**Comment by UkonnRa** [comment]
I get your point. If so I will just use `context` as the data

**Comment by zepatrik** [comment]
I mean if we can refactor it in some way to improve the usability then we're definitely up for it.

**Comment by aeneasr** [comment]
Hm I would be interested to see different approaches to i18n. I know the old systems that e.g gettext/PHP used but those were really hard to work with (.po files). I'm definitely open to improve this! Maybe we could have a human readable string and one with replacements?

**Pull request closed without merging**
