### PR TITLE
docs: add FAQ to sidebar

### PR DESCRIPTION
**Pull request by vinckr**
Since the FAQ is up and ready, its time to add it to the sidebar and let loose on our users.
There will be some documentation and infrastructure around how we generate the faq.yaml in the coming days.

Changes have been tested locally and are working.
@zepatrik 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by zepatrik** [comment]
The faq page itself seems to not work: https://www.ory.sh/kratos/docs/next/faq/

**Comment by vinckr** [comment]
Hm weird it works for me?

**Comment by zepatrik** [comment]
Seems like the classes are not properly set, the CSS in the browser is:
```css
li.selected_kPTb.KYC_17Z5~.question_HujK.KYC_17Z5,li.selected_kPTb.attack_3uZN~.question_HujK.attack_3uZN,li.selected_kPTb.database_26Ds~.question_HujK.database_26Ds,li.selected_kPTb.hooks_2Hep~.question_HujK.hooks_2Hep,li.selected_kPTb.kratos_2yIt~.question_HujK.kratos_2yIt,li.selected_kPTb.migration_2_a4~.question_HujK.migration_2_a4,li.selected_kPTb.oidc_2cNm~.question_HujK.oidc_2cNm,li.selected_kPTb.registration_2Ycw~.question_HujK.registration_2Ycw,li.selected_kPTb.security_3g0G~.question_HujK.security_3g0G,li.selected_kPTb.spa_3Mr_~.question_HujK.spa_3Mr_,li.selected_kPTb.traits_2Mgu~.question_HujK.traits_2Mgu,li.selected_kPTb.user_1-7y~.question_HujK.user_1-7y,li.selected_kPTb.validation_NOQ0~.question_HujK.validation_NOQ0,pre code {
    display: inline
}
```

while the elements have the classes:

```html
<li class="selected_1j8o spa_src-theme- pills pills__item styles.pills__item--active">
  #spa
</li>
<br>
<br>
<div class="question_src-theme- kratos_src-theme- database_src-theme-">
  #kratos #database
<br>
<p>...</p>
```

**Comment by zepatrik** [comment]
Right, it renders. But click on a tag....

**Comment by vinckr** [comment]
Right. No idea, works perfectly when I build locally, need to check whats happening.

**Comment by zepatrik** [comment]
It is a problem with the CSS classes and how they are set.

**Comment by aeneasr** [comment]
I think the custom CSS classes are not an optimal solution anyways. Maybe @Benehiko could help you refactor that to be more simple - using plain javascript to show/hide the buttons etc.

**Comment by zepatrik** [comment]
It works now: https://www.ory.sh/kratos/docs/next/faq/

**Review by zepatrik — APPROVED** [review]

**Pull request merged**
