### PR TITLE
fix: duplicate messages in recovery flow

### PR DESCRIPTION
**Pull request by erolkskn**
## Related issue(s)
#2512 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I am following the [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security. vulnerability, 
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Review by aeneasr — CHANGES_REQUESTED** [review]
Thank you. Unfortunately, several test suites are failing. Can you please address the failing tests? My hunch says that you can't just reset the messages there as it will cause some messages to be missing, and will need to use another approach.

**Comment by erolkskn** [comment]
> Thank you. Unfortunately, several test suites are failing. Can you please address the failing tests? My hunch says that you can't just reset the messages there as it will cause some messages to be missing, and will need to use another approach.

Thanks for your review, first error was about linter so i corrected it. But the problem with **e2e tests** doesn't seem to be caused by this commit, all the test suites related to **recovery** are actually passed, seems like there is a problem with oidc tests. Exact same errors happened after the commit aa6eb13c1c42c11354074553fac9c90ee0a8999e. https://github.com/ory/kratos/runs/7325177589?check_suite_focus=true (which is parent commit of this commit). I can try to fix them up too, but i'm not sure whether i should create a new pr for it or continue with this one.

**Comment by aeneasr** [comment]
I reran the suite to see if it is a flaky test, but apparently they are still failing. All other branches are passing though. I do think it has to do something with the changes in this PR!

Regarding the change itself, could you please add a test case that ensures that we don't regress with this in the future? Imagine someone else moving this line of code because they don't understand it's there -> the functionality is broken again because we have no tests.

Thank you :)

**Comment by erolkskn** [comment]
I didn't mean that "tests are flaky" but rather i think tests are failing due to the commit aa6eb13c1c42c11354074553fac9c90ee0a8999e. Your commit from 5 hours ago had the exact same problem in **e2e tests** . https://github.com/ory/kratos/runs/7369485507?check_suite_focus=true d1b6b40aa9dcc7a3ec9237eec28c4fa55f0b8627. Ofc i can add tests, but no matter what i will do tests won't run successfully because test cases doesn't fail because of this commit. I prepared some screenshots in order to explain it better. Here are the screenshots of pipeline logs of commit aa6eb13c1c42c11354074553fac9c90ee0a8999e (i strongly believe that tests are failing due to that commit), your commit from 5 hours ago d1b6b40aa9dcc7a3ec9237eec28c4fa55f0b8627, and this one. They are all failing in the exact same way 5 of OIDC Suite Cases are failing 

**Pipeline logs of commit aa6eb13c1c42c11354074553fac9c90ee0a8999e.**

first

**Pipeline logs of commit d1b6b40aa9dcc7a3ec9237eec28c4fa55f0b8627. That's the one you committed 5 hours ago**

aenasr

**Pipeline logs of this commit**

this

**Comment by aeneasr** [comment]
Awesome, thanks! I think this looks much better now :) I rebased on master which hopefully resolves some of the flaky tests :)

**Review by aeneasr — APPROVED** [review]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Comment by aeneasr** [comment]
Code LGTM, let's wait for CI :)

**Comment by vinckr** [comment]
Hello @erolkskn   
Congrats on merging your first PR in Ory 🎉 !
Your contribution will soon be helping secure millions of identities around the globe 🌏. 
As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. 
[Please drop me an email and I will forward you the form to claim your Ory swag!](mailto:vincent@ory.sh)

**Comment by erolkskn** [comment]
> Hello @erolkskn Congrats on merging your first PR in Ory tada ! Your contribution will soon be helping secure millions of identities around the globe earth_asia. As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. [Please drop me an email and I will forward you the form to claim your Ory swag!](mailto:vincent@ory.sh)

Oh what a nice gesture, thank you guys for that :slightly_smiling_face:

**Pull request merged**
