### PR TITLE
fix: change SMTP config validation from URI to a Regex pattern

### PR DESCRIPTION
**Pull request by noliva**
## Related issue

#1435

## Proposed changes

SMTP validation requires the connection string to be a valid URI, however, AWS SES adds invalid characters to the password, failing validation

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further comments

We match against `SMTP://` or `SMTPS://` plus a valid string after.

### CODE REVIEW

**Comment by aeneasr** [comment]
Unfortunately, for some reason, the CircleCI tests are not running. Do you maybe follow your/a fork of this repository on CircleCI? If so, you need to unsubscribe / unwatch from that CircleCI project. Then, make another push to your branch using:

```
$ git commit --amend --allow-empty
$ git push --force
```

That should get the CI running! Thank you :)

**Comment by noliva** [comment]
I have disabled CircleCI in my end and pushed force a new commit 😄 . Hopefully, it will work this time 👍

**Comment by aeneasr** [comment]
It finally triggered :)

**Comment by aeneasr** [comment]
Great, thank you!

**Pull request merged**
