### PR TITLE
feat: Vue Standalone

### PR DESCRIPTION
**Pull request by timalanfarrow**
This change introduces updated Docker configuration for a standalone Vue UI. It references a docker image that I published based off of this public repository: [timalanfarrow/kratos-selfservice-ui-vue3-typescript.git](https://github.com/timalanfarrow/kratos-selfservice-ui-vue3-typescript). I figured I would include my image (published on Docker hub, see [`#2202`](https://github.com/ory/kratos/issues/2202)) so that you can easily pull and test it, but I don't think it should be merged until it references an image managed by Ory.

## Related issue(s)

[`#2202`](https://github.com/ory/kratos/issues/2202)

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

## Further Comments

I left most of the context necessary for discussion in [`#2202`](https://github.com/ory/kratos/issues/2202)

### CODE REVIEW

**Comment by aeneasr** [comment]
The example has been merged and released in the documentation. We could also add a docker-compose guide for it, now that I think about it ... @vinckr

**Comment by vinckr** [comment]
> The example has been merged and released in the documentation. We could also add a docker-compose guide for it, now that I think about it ... @vinckr

Yea, I was thinking maybe I write up a small blogpost together with @timalanfarrow so he gets some recognition too, and then we link it in the documentation where appropriate; Wdyt?

**Comment by timalanfarrow** [comment]
@vinckr I'm totally up for that! I think I should have time this weekend to work on a blog post. We can collaborate in Slack.

**Comment by aeneasr** [comment]
That would be cool! I think we can use the docker-compose created in this PR to show the example with a few commands? If people just want to see the example without setting up Ory Kratos in Docker, you could also use `https://playground.projects.oryapis.com` (or any other `<project>.projects.oryapis.com`) as a fall back!

**Comment by aeneasr** [comment]
As per discussion I'll be closing this PR :) The vue app is officially in the docs also!

**Pull request closed without merging**
