### PR TITLE
chore(docs): add google to supported providers in ID Token doc strings

### PR DESCRIPTION
**Pull request by jonas-jonas**
## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Review by aeneasr — COMMENTED** [review]
In fact, I think this works for almost every openid connect provider?

**Comment by jonas-jonas** [comment]
No it's only implemented for Google and Apple yet.

**Comment by aeneasr** [comment]
Are you sure?

https://github.com/ory/kratos/blob/ad5fb09687f863e7c5d45868d0b8f5ec2d965372/selfservice/strategy/oidc/strategy.go#L706

**Comment by aeneasr** [comment]
Screenshot 2024-08-07 at 16 13 36

**Comment by jonas-jonas** [comment]
That method expects the provider to implement `IDTokenVerifier`, which only google and apple do.

https://github.com/ory/kratos/blob/ad5fb09687f863e7c5d45868d0b8f5ec2d965372/selfservice/strategy/oidc/strategy.go#L707

**Comment by aeneasr** [comment]
Makes sense!

**Review by aeneasr — APPROVED** [review]

**Pull request merged**
