### PR TITLE
fix: return_to used if specified

### PR DESCRIPTION
**Pull request by reginbald**
The goal of this pull request is to make minimal changes that allow Kratos to support multiple browser applications on separate domains to handle their own login/logout/etc UI. This is done by using the return_to URL if specified to redirect the user and returning an additional flow type (login/registration/...) during error condition in order for the application to inform the user of the error situation. 

This means that there can be two browser applications on separate subdomains, app1.example.com and app2.example.com (white listed in the Kratos allowed_return_urls config). Each application would add its URL with the return_to parameter during flow creation to inform Kratos of which application initiated the flow. After the execution of the flow Kratos will redirect the user to the application that initiated the flow if the ReturnTo property was specified otherwise use the default urls from the Kratos configuration.

If a flow execution ends with an error the user will be redirected back to the application with both the flow id and flow type, allowing the application to query Kratos for the error message to inform the user. 

By returning the flow type Kratos no longer forces the application to have separate routes for each flow.

## Related issue(s)

Based on the discussion from [Issue: 3106](https://github.com/ory/kratos/issues/3106)

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Comment by reginbald** [comment]
This will of course break the expectation that on error the user will be redirected to the url specified in the kratos configuration on error

**Review by aeneasr — CHANGES_REQUESTED** [review]
Thank you for your work on this PR! Unfortunately, I don't think that we can merge it as is. It breaks many current assumptions around how the UI works, and it introduces significant complexity (that is not yet addressed in the PR properly, and a lot of work) because it basically deals with multi-tenant login, which is not supported by Ory Kratos itself.

My recommendation would be to decide this in your UI app instead. There, you can implement redirects in any way you want. Ory Kratos delivers you with all the information required (e.g. the initial requested URL) which may contain URL parameters you can use for further propagation.

Thank you for understanding!

**Comment by reginbald** [comment]
I was expecting that :), Thanks for your feedback. Do you think some solution is on the roadmap or is this something you don't want to support? I could also set a side some time during the weekend to create a proper proposal for you.

**Comment by reginbald** [comment]
Good to know, thank you :)

**Pull request closed without merging**
