### PR TITLE
Selfservice: change flow sort, oidc below password

### PR DESCRIPTION
**Pull request by afreakk**
Changed the order, to have password group above oidc, to fix so the top submit  button is not the oidc.
So enter = password, not oidc

There might be a reason for the previous order I dont know about.  
But using nextjs  or nodejs selfservice reference  implementation with oidc enabled, it will render oidc on top which causes enter press inside a input to trigger the oidc action.  
Which is very annoying :)  
image
image

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I am following the [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security.
      vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
      maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

## Further Comments
I have not tested webauthn and the others, so, dont know if this is suboptimal in relation to them.

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you, that is indeed annoying! But instead of re-ordering, could we use [tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) instead?

**Comment by afreakk** [comment]
yeah, that would require supporting code in the frontends though, and would still render the `google login` button above the rest.  
I dont care much about that, but I think normally `login with google` is below the usr/pw input fields.

**Comment by aeneasr** [comment]
> yeah, that would require supporting code in the frontends though

That is relatively straight forward :) Basically just needs to be added:

https://github.com/ory/kratos-selfservice-ui-node/blob/7d5ac8831dc50708d4a0df4495ba6dd450595c21/views/partials/ui_node_input_default.hbs#L8-L14

and here:

https://github.com/ory/kratos-selfservice-ui-react-nextjs/blob/f3c98d927a2481688068c4e262298c05d70411e6/pkg/ui/NodeInputDefault.tsx#L27-L37

**Comment by afreakk** [comment]
Instead of tabindex, could we use `type=button` instead of `type=submit` on oidc login?
That works actually.

**Comment by aeneasr** [comment]
As there hasn't been any progress on this PR, I'm closing it as we do not want to change the order globally. But you're of course always welcomed to contribute changes to tabindex as discussed :)

**Pull request closed without merging**
